# Imports
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: media.yml }
    - { resource: sonata.yml }

# Framework
framework:
    translator:      { fallbacks: [ "%locale%" ] }
    validation:      { enable_annotations: true }
    secret:          "%secret%"
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    fragments:       ~
    csrf_protection: ~
    router:
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    templating:
        engines: [ "twig" ]
    session:
        handler_id:  ~
    http_method_override: true

# Twig
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "bootstrap_3_layout.html.twig"
        - "SonataCoreBundle:Form:datepicker.html.twig"
    globals:
        google_analytics_enabled: "%google_analytics_enabled%"
        google_analytics_account: "%google_analytics_account%"
        main_brand_title:         "Asbel Esteve"
        admin_tag_version:        "v1.0.22"

# Assetic
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    java:           "%assetic_path_java%"
    node:           "%assetic_path_node%"
    bundles:        [ AppBundle ]
    filters:
        cssrewrite: ~
        less:
            node:       "%assetic_path_node%"
            node_paths: [ "%assetic_path_node_modules%" ]
    assets:
        mycss:
            inputs:
                - "@AppBundle/Resources/public/css/main.less"
        myjs:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js"

# Doctrine
doctrine:
    dbal:
        server_version: "%database_server_version%"
        driver:         "%database_driver%"
        host:           "%database_host%"
        port:           "%database_port%"
        dbname:         "%database_name%"
        user:           "%database_user%"
        password:       "%database_password%"
        charset:        UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../src/AppBundle/DoctrineMigrations"
    namespace: AppBundle\DoctrineMigrations

# Swiftmailer
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# CKEditor
ivory_ck_editor:
    inline: false
    configs:
        my_config:
            toolbar: standard

# Stof Doctrine Extensions
stof_doctrine_extensions:
    default_locale:       "%locale%"
    translation_fallback: true
    orm:
        default:
            softdeleteable: true
            timestampable:  true
            sluggable:      true
            translatable:   false
            sortable:       false
            tree:           false

# FOS User
fos_user:
    db_driver:      orm
    firewall_name:  admin
    user_class:     AppBundle\Entity\User
    group:
        group_class:   AppBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager
