services:
# Sonata Admins
    admin.contact:
        class: AppBundle\Admin\ContactMessageAdmin
        arguments: [ ~, AppBundle\Entity\ContactMessage, AppBundle:Admin\ContactMessageAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Contact Messages", group: "Web" }
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [ ~, AppBundle\Entity\Category, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Categories", group: "Web" }
    admin.film:
        class: AppBundle\Admin\FilmAdmin
        arguments: [ ~, AppBundle\Entity\Film, AppBundle:Admin\FilmAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Content", group: "Web" }
    admin.filmimage:
        class: AppBundle\Admin\FilmImageAdmin
        arguments: [ ~, AppBundle\Entity\FilmImage, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Image Films", group: "Web", show_in_dashboard: false }
    admin.page:
        class: AppBundle\Admin\PageAdmin
        arguments: [ ~, AppBundle\Entity\Page, AppBundle:Admin\PageAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Page", group: "Web" }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Users", group: "Admin" }
# Sonata Blocks
    admin.block.messages:
        class: AppBundle\Admin\Block\PendingMessagesBlock
        tags:
            - { name: sonata.block }
        arguments: [ "sonata.admin.block.messages", "@templating", "@doctrine.orm.entity_manager" ]
# Menus
    app.frontend_menu_builder:
        class: AppBundle\Menu\FrontendMenuBuilder
        arguments: [ "@knp_menu.factory", "@doctrine.orm.entity_manager" ]
    app.frontend_main_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createMainMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: main }
    app.frontend_bottom_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createBottomMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: bottom }
# Twig
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
