services:
    # Menu
    app.frontend_menu_builder:
        class: AppBundle\Menu\FrontendMenuBuilder
        arguments: [ '@knp_menu.factory' ]
    app.frontend_main_menu:
        class: Knp\Menu\MenuItem
        factory: [ '@app.frontend_menu_builder', createMainMenu ]
        arguments: [ '@request_stack' ]
        tags:
            - { name: knp_menu.menu, alias: main }
