services:
# Sonata Admins
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuaris", group: "Administrador" }
# Sonata Blocks
    admin.block.messages:
        class: AppBundle\Admin\Block\PendingMessagesBlock
        tags:
            - { name: sonata.block }
        arguments: [ "sonata.admin.block.messages", "@templating", "@doctrine.orm.entity_manager" ]
# Menus
    app.frontend_menu_builder:
        class: AppBundle\Menu\FrontendMenuBuilder
        arguments: [ '@knp_menu.factory' ]
    app.frontend_main_menu:
        class: Knp\Menu\MenuItem
        factory: [ '@app.frontend_menu_builder', createMainMenu ]
        arguments: [ '@request_stack' ]
        tags:
            - { name: knp_menu.menu, alias: main }
    app.frontend_bottom_menu:
        class: Knp\Menu\MenuItem
        factory: [ '@app.frontend_menu_builder', createBottomMenu ]
        arguments: [ '@request_stack' ]
        tags:
            - { name: knp_menu.menu, alias: bottom }
# Twig
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
