# Admin
sonata_admin:
    title: "Asbel Esteve"
    title_logo: "/bundles/app/images/backend-favicon.png"
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    10
    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout: "::Admin/layout.html.twig"
        show:   "::Admin/show.html.twig"
    dashboard:
        groups:
            Web:
                icon: "<i class='fa fa-chrome'></i>"
            Admin:
                icon: "<i class='fa fa-cog'></i>"
        blocks:
            -
                position: top
                type: sonata.block.service.text
                class: col-md-12
                settings:
                    content: >
                        <h1 style="margin-top:0">Content Management System</h1>
            -
                position: top
                type: sonata.admin.block.admin_list
                class: col-md-6
                settings:
                    groups: [ Web ]
            -
                position: top
                type: admin.block.messages
                class: col-md-6
            -
                position: top
                type: sonata.admin.block.admin_list
                class: col-md-6
                settings:
                    groups: [ Admin ]
            -
                position: bottom
                type: sonata.block.service.text
                class: col-md-12
                settings:
                    content: >
                        <div><hr style="margin-top:40px;border-top:solid 1px #d2d6de"><p><i class="fa fa-info-circle"></i> Technical support at <a href="mailto:suport@flux.cat?subject=Asbel Esteve CMS help" style="color:#000">suport@flux.cat</a></p></div>

# Block
sonata_block:
    default_contexts: [ cms ]
    blocks:
        sonata.user.block.menu:         ~
        sonata.block.service.text:      ~
        sonata.admin.block.admin_list:  ~
        admin.block.messages:           ~

# Doctrine ORM Admin
sonata_doctrine_orm_admin:
    templates:
        form:
            - "::Admin/Forms/custom_checkbox_form_template_hack.html.twig"

# SEO
sonata_seo:
    encoding: UTF-8
    page:
        default:  sonata.seo.page.default
        head:
            'xmlns':    "http://www.w3.org/1999/xhtml"
            'xmlns:og': "http://opengraphprotocol.org/schema/"

# User
sonata_user:
    security_acl: true
    manager_type: orm
